# Generated by Django 4.1.10 on 2023-12-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='time_interval_on_create_events',
            field=models.PositiveIntegerField(default=1, verbose_name='Указать временной интервал на создание событий(в секундах)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='time_interval_on_update_events',
            field=models.PositiveIntegerField(default=1, verbose_name='Указать временной интервал на обновление событий(в секундах)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='time_interval_on_update_events_statistic',
            field=models.PositiveIntegerField(default=1, verbose_name='Указать временной интервал на обновление статистик событий(в секундах)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='update_players_in_team',
            field=models.BooleanField(default=False, verbose_name='Обновить игроков во всех комнадах'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='yandex_metrika_link',
            field=models.TextField(default=1, verbose_name='Ссылка Яндекс Метрика'),
            preserve_default=False,
        ),
    ]
