# Generated by Django 4.2 on 2023-12-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_generalsettings_time_interval_on_create_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='headerImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Шапка сайта'),
        ),
    ]
