# Generated by Django 4.2 on 2023-12-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_generalsettings_headerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображениe'),
        ),
    ]
