# Generated by Django 4.2 on 2023-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_pages_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='other_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на другой источник'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True, verbose_name='Ссылка на сайте'),
        ),
    ]
