# Generated by Django 4.2 on 2023-12-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_pages_other_link_alter_pages_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, verbose_name='Ссылка на сайте'),
        ),
    ]
