# Generated by Django 4.2 on 2023-12-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_pages_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'GMT-12:00'), (2, 'GMT-11:00'), (3, 'GMT-10:00'), (4, 'GMT-9:00'), (5, 'GMT-8:00'), (6, 'GMT-7:00'), (7, 'GMT-6:00'), (8, 'GMT-5:00'), (9, 'GMT-4:00'), (10, 'GMT-3:00'), (11, 'GMT-2:00'), (12, 'GMT-1:00'), (13, 'GMT±00:00'), (14, 'GMT+01:00'), (15, 'GMT+02:00'), (16, 'GMT+03:00'), (17, 'GMT+04:00'), (18, 'GMT+05:00'), (19, 'GMT+06:00'), (20, 'GMT+07:00'), (21, 'GMT+08:00'), (22, 'GMT+09:00'), (23, 'GMT+10:00'), (24, 'GMT+11:00'), (25, 'GMT+12:00')], null=True, verbose_name='Часовой пояс'),
        ),
    ]
