# Generated by Django 4.2 on 2024-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_user_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='time_interval_on_create_events',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='time_interval_on_update_events',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='time_interval_on_update_events_statistic',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='update_players_in_team',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='rapidapi_key_events',
            field=models.TextField(default=1, verbose_name='FlashScoreRapid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='rapidapi_key_stream',
            field=models.TextField(default=1, verbose_name='SoccerVideosRapid'),
            preserve_default=False,
        ),
    ]
