# Generated by Django 4.2 on 2024-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_generalsettings_email_host_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='email_host',
            field=models.TextField(default=1, verbose_name='Email Site HOST'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='email_port',
            field=models.TextField(default=1, verbose_name='Email Site PORT'),
            preserve_default=False,
        ),
    ]
