# Generated by Django 4.1.10 on 2024-02-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_generalsettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='email_use_ssl',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='email_use_tls',
        ),
    ]
