# Generated by Django 4.1.7 on 2023-11-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameStatistic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 период"),
                            (2, "2 период"),
                            (3, "3 период"),
                            (4, "4 период"),
                            (5, "5 период"),
                            (6, "Все"),
                        ],
                        default=1,
                        verbose_name="Период",
                    ),
                ),
                ("name", models.CharField(max_length=500, null=True, verbose_name="Название статистики")),
                ("home", models.CharField(max_length=150, verbose_name="Кол-во у дома")),
                ("away", models.CharField(max_length=150, verbose_name="Кол-во у гостей")),
                ("description", models.TextField(null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Игровая статистика",
                "verbose_name_plural": "Игровые статистики",
            },
        ),
        migrations.CreateModel(
            name="H2H",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("home_score", models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Очки дома")),
                (
                    "away_score",
                    models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Очки гостей"),
                ),
                ("api_h2h_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="ID API")),
                ("name", models.CharField(max_length=500, null=True, verbose_name="Название")),
                (
                    "home_team_ID",
                    models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="ID Дома "),
                ),
                (
                    "away_team_ID",
                    models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="ID Гостей"),
                ),
                ("home_team_NAME", models.CharField(blank=True, max_length=500, null=True, verbose_name="NAME Дома")),
                (
                    "home_team_LOGO",
                    models.ImageField(
                        blank=True,
                        default="default/generals/no-image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="home_team_LOGO",
                    ),
                ),
                ("away_team_NAME", models.CharField(blank=True, max_length=500, null=True, verbose_name="NAME Гостей")),
                (
                    "away_team_LOGO",
                    models.ImageField(
                        blank=True,
                        default="default/generals/no-image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="away_team_LOGO",
                    ),
                ),
                ("league", models.CharField(max_length=500, null=True, verbose_name="Название")),
                (
                    "league_logo",
                    models.ImageField(
                        blank=True,
                        default="default/generals/no-image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Изображения",
                    ),
                ),
                ("start_at", models.DateTimeField(null=True, verbose_name="Начало")),
                ("h_result", models.CharField(blank=True, max_length=500, null=True, verbose_name="H_RESULT")),
                ("team_mark", models.CharField(blank=True, max_length=500, null=True, verbose_name="TEAM_MARK")),
            ],
            options={
                "verbose_name": "H2H",
                "verbose_name_plural": "H2H",
            },
        ),
        migrations.CreateModel(
            name="Periods",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_api_id", models.PositiveIntegerField(verbose_name="ID API")),
                ("home_score", models.IntegerField(verbose_name="Очки дома")),
                ("away_score", models.IntegerField(verbose_name="Очки гостей")),
                ("period_number", models.PositiveIntegerField(verbose_name="Номер периода")),
            ],
            options={
                "verbose_name": "Период",
                "verbose_name_plural": "Периоды",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("player_id", models.PositiveIntegerField(null=True, verbose_name="ID игрока API")),
                ("slug", models.SlugField(max_length=160, unique=True, verbose_name="Ссылка")),
                ("name", models.CharField(max_length=500, null=True, verbose_name="Имя игрока")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="default/generals/no-image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Изображения",
                    ),
                ),
                ("position_name", models.CharField(max_length=500, null=True, verbose_name="Позиция")),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                ("main_player", models.BooleanField(default=False, verbose_name="Состояние замены")),
                ("reiting", models.CharField(max_length=500, null=True, verbose_name="Рейтинг")),
                ("number", models.CharField(max_length=500, null=True, verbose_name="Номер")),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
            },
        ),
        migrations.CreateModel(
            name="Points",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("homePoint", models.CharField(max_length=150, verbose_name="Очки дома")),
                ("awayPoint", models.CharField(max_length=150, verbose_name="Очки гостей")),
            ],
            options={
                "verbose_name": "Теннисные поинты",
                "verbose_name_plural": "Теннисные поинты",
            },
        ),
        migrations.CreateModel(
            name="Rubrics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500, null=True, verbose_name="Название")),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                ("title", models.CharField(max_length=500, null=True, verbose_name="Заголовок")),
                ("api_id", models.PositiveIntegerField(null=True, verbose_name="ID спорта")),
                ("content", models.TextField(max_length=500, null=True, verbose_name="Мета-описание")),
                ("slug", models.SlugField(max_length=160, unique=True, verbose_name="Ссылка")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        default="default/generals/no-image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Иконка цветная",
                    ),
                ),
                (
                    "icon2",
                    models.ImageField(
                        blank=True,
                        default="default/generals/no-image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Иконка черная",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        default="default/generals/no-image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Обложка",
                    ),
                ),
                ("sortable", models.PositiveIntegerField(null=True, unique=True, verbose_name="Сортивароть")),
                ("second_api", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Рубрики",
                "verbose_name_plural": "Рубрики",
            },
        ),
        migrations.CreateModel(
            name="TennisGames",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("game", models.CharField(max_length=150, verbose_name="Игра")),
                ("home_score", models.CharField(max_length=150, verbose_name="Очки дома")),
                ("away_score", models.CharField(max_length=150, verbose_name="Очки гостей")),
                ("serving", models.CharField(max_length=15, verbose_name="Подача")),
                ("points", models.ManyToManyField(blank=True, to="events.points", verbose_name="Очки")),
            ],
            options={
                "verbose_name": "Теннисные игры",
                "verbose_name_plural": "Теннисные игры",
            },
        ),
        migrations.CreateModel(
            name="TennisPoints",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_id_tp", models.CharField(max_length=150, verbose_name="ID API ")),
                ("set", models.CharField(max_length=150, verbose_name="Сэт")),
                ("games", models.ManyToManyField(blank=True, to="events.tennisgames", verbose_name="Теннисные игры")),
            ],
            options={
                "verbose_name": "Теннисные очки",
                "verbose_name_plural": "Теннисные очки",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=500, null=True, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True, verbose_name="Ссылка")),
                ("api_team_id", models.PositiveIntegerField(null=True, verbose_name="ID команды")),
                ("second_api_team_id", models.CharField(max_length=150, null=True, verbose_name="ID команды")),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="default/generals/no-image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Изображения",
                    ),
                ),
                ("h2h", models.ManyToManyField(blank=True, to="events.h2h", verbose_name="H2H")),
                ("players", models.ManyToManyField(to="events.player", verbose_name="Игроки")),
                (
                    "rubrics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.rubrics", verbose_name="Рубрики"
                    ),
                ),
            ],
            options={
                "verbose_name": "Команда",
                "verbose_name_plural": "Команды",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("season_name", models.CharField(max_length=500, null=True, verbose_name="Название сезона")),
                ("league_name", models.CharField(max_length=500, null=True, verbose_name="Название лиги")),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True, verbose_name="Ссылка")),
                ("league_id", models.PositiveIntegerField(null=True, verbose_name="ID лиги")),
                ("season_id", models.PositiveIntegerField(null=True, verbose_name="ID сезона")),
                ("season_second_api_id", models.CharField(max_length=500, null=True, verbose_name="API ID 2")),
                (
                    "logo_league",
                    models.ImageField(
                        blank=True,
                        default="default/generals/no-image.jpg",
                        null=True,
                        upload_to="",
                        verbose_name="Изображения",
                    ),
                ),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                ("popular", models.BooleanField(default=False)),
                ("country", models.CharField(blank=True, max_length=500, null=True, verbose_name="Страна")),
                (
                    "rubrics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.rubrics", verbose_name="Рубрики"
                    ),
                ),
            ],
            options={
                "verbose_name": "Лига",
                "verbose_name_plural": "Лиги",
            },
        ),
        migrations.CreateModel(
            name="PopularSeasons",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(verbose_name="Позиция в списке ")),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.season", verbose_name="Лига"
                    ),
                ),
            ],
            options={
                "verbose_name": "Популярная Лига",
                "verbose_name_plural": "Популярные Лиги",
            },
        ),
        migrations.CreateModel(
            name="Incidents",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("incident_type", models.CharField(max_length=500, null=True, verbose_name="Тип")),
                ("player_team", models.PositiveIntegerField(null=True, verbose_name="Событие команды")),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                ("card_type", models.CharField(blank=True, max_length=150, verbose_name="Цвет карточки")),
                ("time", models.CharField(blank=True, max_length=150, verbose_name="Время события")),
                ("inj_time", models.CharField(blank=True, max_length=150, verbose_name="Доп время")),
                ("scoring_team", models.CharField(blank=True, max_length=150, verbose_name="Команда забившая")),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents_player",
                        to="events.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "player_two_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents_player_two_in",
                        to="events.player",
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "rubrics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.rubrics", verbose_name="Рубрики"
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие(голы и тд)",
                "verbose_name_plural": "События(голы и тд)",
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("event_api_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="ID API")),
                (
                    "second_event_api_id",
                    models.CharField(blank=True, max_length=150, null=True, verbose_name="ID API 2 "),
                ),
                ("data", models.DateTimeField(auto_now=True)),
                ("start_at", models.DateTimeField(null=True, verbose_name="Начало")),
                ("name", models.CharField(max_length=500, null=True, verbose_name="Название")),
                ("description", models.TextField(null=True, verbose_name="Описание")),
                ("title", models.CharField(max_length=500, null=True, verbose_name="Заголовок")),
                ("content", models.TextField(max_length=500, null=True, verbose_name="Мета-описание")),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True, verbose_name="Ссылка")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Прямой эфир"), (2, "Завершенные"), (3, "Предстоящие"), (4, "Отменён")],
                        default=3,
                        verbose_name="Статус",
                    ),
                ),
                ("home_score", models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Очки дома")),
                (
                    "away_score",
                    models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Очки гостей"),
                ),
                ("half", models.CharField(blank=True, max_length=150, null=True, verbose_name="Половина")),
                ("reschedule", models.BooleanField(default=False, verbose_name="Событие перенесено по времени")),
                (
                    "away_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_team",
                        to="events.team",
                        verbose_name="Гостевая комнада",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_team",
                        to="events.team",
                        verbose_name="Домашняя комнада",
                    ),
                ),
                (
                    "incidents",
                    models.ManyToManyField(blank=True, to="events.incidents", verbose_name="События(голы и тд)"),
                ),
                ("periods", models.ManyToManyField(blank=True, to="events.periods", verbose_name="Половина")),
                (
                    "rubrics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.rubrics",
                        verbose_name="Рубрики",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.season",
                        verbose_name="Сезон",
                    ),
                ),
                (
                    "statistic",
                    models.ManyToManyField(blank=True, to="events.gamestatistic", verbose_name="Статистика за матч"),
                ),
                (
                    "tennis_points",
                    models.ManyToManyField(blank=True, to="events.tennispoints", verbose_name="Теннисные очки"),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
    ]
