# Generated by Django 4.1.10 on 2023-12-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='h2h',
        ),
        migrations.AddField(
            model_name='events',
            name='h2h',
            field=models.ManyToManyField(blank=True, to='events.h2h', verbose_name='H2H'),
        ),
        migrations.AlterField(
            model_name='gamestatistic',
            name='period',
            field=models.CharField(max_length=500, verbose_name='Период'),
        ),
    ]
