# Generated by Django 4.1.10 on 2023-12-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_team_h2h_events_h2h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='league_id',
            field=models.CharField(max_length=500, null=True, verbose_name='ID лиги'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_id',
            field=models.CharField(max_length=500, null=True, verbose_name='ID сезона'),
        ),
    ]
