# Generated by Django 4.1.10 on 2023-12-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_season_league_id_alter_season_season_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, verbose_name='Ссылка'),
        ),
    ]
