# Generated by Django 4.1.10 on 2023-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_country_alter_season_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(default='default/russia_flag.jpg', upload_to='', verbose_name='Флаг'),
        ),
    ]
