# Generated by Django 4.1.10 on 2023-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_country_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='logo_league',
            field=models.ImageField(blank=True, default='default/generals/no-image.jpg', max_length=500, null=True, upload_to='', verbose_name='Изображения'),
        ),
    ]
