# Generated by Django 4.1.10 on 2023-12-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_season_logo_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_at',
            field=models.CharField(max_length=500, null=True, verbose_name='Начало'),
        ),
    ]
