# Generated by Django 4.2 on 2023-12-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_country_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='logo_league',
            field=models.TextField(blank=True, null=True, verbose_name='Изображения'),
        ),
    ]
