# Generated by Django 4.2 on 2023-12-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_season_logo_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.TextField(blank=True, null=True, verbose_name='Изображения'),
        ),
    ]
