# Generated by Django 4.2 on 2024-01-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_stages_alter_season_season_id_season_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=500, null=True, verbose_name='Тип события')),
                ('participant_name', models.CharField(max_length=500, null=True, verbose_name='Имя игрока')),
                ('incident_name', models.CharField(max_length=500, null=True, verbose_name='Название события')),
                ('participant_id', models.CharField(max_length=500, null=True, verbose_name='ID API события')),
            ],
            options={
                'verbose_name': 'Участники инцидента',
                'verbose_name_plural': 'Участники инцидента',
            },
        ),
        migrations.RenameField(
            model_name='incidents',
            old_name='player_team',
            new_name='incident_team',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='description',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='incident_type',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='inj_time',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='player',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='player_two_in',
        ),
        migrations.RemoveField(
            model_name='incidents',
            name='scoring_team',
        ),
        migrations.AddField(
            model_name='events',
            name='h2h_status',
            field=models.BooleanField(default=False, verbose_name='H2H созданы'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='incident_api_id',
            field=models.CharField(max_length=500, null=True, verbose_name='incident_api_id'),
        ),
        migrations.AlterField(
            model_name='periods',
            name='period_number',
            field=models.CharField(max_length=150, verbose_name='Номер периода'),
        ),
        migrations.AddField(
            model_name='incidents',
            name='incident_participants',
            field=models.ManyToManyField(blank=True, to='events.incidentparticipants', verbose_name='Участники инцидента'),
        ),
    ]
