# Generated by Django 4.2 on 2024-01-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_incidentparticipants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='match_stream_link',
            field=models.TextField(default=1, verbose_name='Ссылка на онлайн трансляцию'),
            preserve_default=False,
        ),
    ]
