# Generated by Django 4.2 on 2024-01-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_events_match_stream_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periods',
            name='event_api_id',
            field=models.CharField(max_length=150, verbose_name='ID API'),
        ),
    ]
