# Generated by Django 4.2 on 2024-01-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_events_events_even_name_8aa231_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='description',
        ),
        migrations.RemoveField(
            model_name='player',
            name='description',
        ),
    ]
