# Generated by Django 4.2 on 2024-01-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_remove_events_description_remove_player_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='description',
        ),
    ]
