# Generated by Django 4.2 on 2024-01-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_remove_season_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
