# Generated by Django 4.2 on 2024-02-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_country_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='sort_by',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция в списке'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popularseasons',
            name='position',
            field=models.PositiveIntegerField(verbose_name='Позиция в списке'),
        ),
    ]
