# Generated by Django 4.2 on 2024-02-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_country_sort_by_alter_popularseasons_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='sort_by',
        ),
    ]
