# Generated by Django 4.2 on 2024-02-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_country_sort_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periods',
            name='period_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Номер периода'),
        ),
    ]
