# Generated by Django 4.2 on 2024-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_periods_period_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='start_at_for_timer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Начало для таймера'),
        ),
    ]
