# Generated by Django 4.2 on 2024-02-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_events_start_at_for_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='player_status',
            field=models.BooleanField(default=False, verbose_name='Игроки созданы'),
        ),
    ]
