# Generated by Django 4.2 on 2024-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_events_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start_at_for_timer',
            field=models.TextField(blank=True, null=True, verbose_name='Начало для таймера'),
        ),
    ]
