# Generated by Django 4.2 on 2024-02-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_events_start_at_for_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='timer_div',
            field=models.TextField(default=1, verbose_name='Див Таймера'),
            preserve_default=False,
        ),
    ]
