# Generated by Django 4.2 on 2024-02-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_events_timer_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time_half_time',
            field=models.TextField(blank=True, null=True, verbose_name='Время перерыва'),
        ),
        migrations.AlterField(
            model_name='events',
            name='match_stream_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на онлайн трансляцию'),
        ),
        migrations.AlterField(
            model_name='events',
            name='timer_div',
            field=models.TextField(blank=True, null=True, verbose_name='Див Таймера'),
        ),
    ]
