# Generated by Django 4.2 on 2024-03-02 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_events_time_half_time_alter_events_match_stream_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=500, null=True, verbose_name='Начало периода')),
                ('end', models.CharField(max_length=500, null=True, verbose_name='Конец периода')),
                ('end_pause', models.CharField(max_length=500, null=True, verbose_name='Конец перерыва периода')),
                ('period', models.CharField(max_length=500, null=True, verbose_name='Длительность матча')),
                ('pause', models.CharField(max_length=500, null=True, verbose_name='Длительность перерыва')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.events', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Таймер',
                'verbose_name_plural': 'Таймер',
            },
        ),
    ]
