# Generated by Django 4.2 on 2024-03-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_timeperiod_last_period_timeperiod_pause_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='fake_end_pause_time',
            field=models.CharField(max_length=500, null=True, verbose_name='Фэк'),
        ),
    ]
