EMAIL_HOST = 'smtp.beget.com'
EMAIL_PORT = '465'
EMAIL_USE_TSL = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'info@eyesofhistory.ru'
EMAIL_HOST_PASSWORD = 'OE%&K8s0'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER